/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as nftSol from "./NFT.sol";
export type { nftSol };
import type * as test from "./test";
export type { test };
export type { KeepersCounter } from "./KeepersCounter";
